#!/bin/bash

set -e

. spack-environments/${ENV_NAME}/ci-variables.bash

#[get-spack--]
if [[ ! -d ${SPACK_PATH} ]]
then
  mkdir -p ${SPACK_PATH}/..
  # A shallow clone is enough, and much faster.
  git clone ${SPACK_REPO} --depth 1 --branch develop ${SPACK_PATH}
fi

cd ${SPACK_PATH}
git checkout -b temp
git branch -D ${SPACK_REF}
git fetch --depth 1 ${SPACK_REPO} ${SPACK_REF}:${SPACK_REF}
git checkout ${SPACK_REF}
git tag ${CI_PIPELINE_ID}
git branch -D temp
cd -
#[--get-spack]
