#!/bin/bash

if [[ ! -d ${MY_SPACK_PATH} ]]
then
  cd ${MY_SPACK_PATH}
  git apply ${CI_PROJECT_DIR}/patches/spack/user-scope.patch
  git commit -am "Moving user scope in spack directory"
  cd -
else
  echo "\$MY_SPACK_PATH = $MY_SPACK_PATH is not a directory,"
  echo "be sure to run get-spack first."
  exit 1
fi
