#!/bin/bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_DIR=$SCRIPT_DIR/..
BASE_PATH=test_dir

SPACK_ENV_PATH=$REPO_DIR

# get-spack variables
export SPACK_REPO=https://github.com/spack/spack.git
export SPACK_PATH=spack
export SPACK_BIN=$SPACK_PATH/bin
export SPACK_REF="${SPACK_REF:-develop}"
export CI_PIPELINE_ID="${CI_PIPELINE_ID:-}"

echo "~~~~~~~~~~~~~ test-blt variables ~~~~~~~~~~~~~~"
  echo SCRIPT_DIR=$SCRIPT_DIR
  echo REPO_DIR=$REPO_DIR
  echo BASE_PATH=$BASE_PATH
  echo SPACK_REPO=$SPACK_REPO
  echo SPACK_PATH=$SPACK_PATH
  echo SPACK_REF=$SPACK_REF
  echo CI_PIPELINE_ID=$CI_PIPELINE_ID
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

rm -rf $BASE_PATH
mkdir $BASE_PATH

cd $BASE_PATH
  # Setup Spack
  $SCRIPT_DIR/get-spack
  cp -R $REPO_DIR/packages/* $SPACK_PATH/var/spack/repos/builtin/packages

  # Load environment and build/test BLT
  mkdir spack-build
  cd spack-build
    $SPACK_BIN/spack env create test1 $REPO_DIR/spack-environments/blt-test/toss3-clang10.yaml
    $SPACK_BIN/spack env activate test1
    $SPACK_BIN/spack concretize
    $SPACK_BIN/spack find -cvl
    $SPACK_BIN/spack install
  cd ..
cd ..
